language: objective-c
osx_image: xcode8.2
xcode_project: Signals.xcodeproj
xcode_scheme: Signals
xcode_sdk: iphonesimulator10.2

script:
  - xcodebuild clean build test -project "Signals.xcodeproj" -scheme "Signals" -destination 'platform=iOS Simulator,id=22FA2149-1241-469C-BF6D-462D3837DB72,OS=10.2'

after_success:
  - bash <(curl -s https://codecov.io/bash)
