language: objective-c
osx_image: xcode9.3
xcode_project: Signals.xcodeproj
xcode_scheme: Signals
xcode_sdk: iphonesimulator11.3

script:
  - xcodebuild clean build test -project "Signals.xcodeproj" -scheme "Signals" -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3'

after_success:
  - bash <(curl -s https://codecov.io/bash)
